/*
##
##  Enhancer for YouTube™
##  =====================
##
##  Author: Maxime RF <https://www.mrfdev.com>
##
##  This file is protected by copyright laws and international copyright
##  treaties, as well as other intellectual property laws and treaties.
##
##  All rights not expressly granted to you are retained by the author.
##  Read the license.txt file for more details.
##
##  © MRFDEV.com - All Rights Reserved
##
*/
(function(p,d){if(!p.efyt){p.efyt=!0;function q(){try{var f=c.getAvailableQualityLevels(),b=d.fullscreenElement?a.qualityembedsfullscreen:a.qualityembeds;0<=f.indexOf(b)?c.setPlaybackQualityRange(b,b):c.setPlaybackQualityRange(f[0],f[0]);5!==c.getPlayerState()&&(u=!0)}catch(e){}}function x(){k.setAttribute("style","display:block!important");clearTimeout(A);A=setTimeout(function(){k.setAttribute("style","display:none!important")},1500)}function B(){var f=d.querySelector(".ytp-popup.ytp-contextmenu");
f&&0<f.getBoundingClientRect().height&&(f.style.display="none");d.body.classList.remove("ytp-contextmenu-hidden")}function D(){var f=d.createElement("style");f.type="text/css";f.textContent="#efyt-player-info{background-color:rgba(0,0,0,0.3);color:#fff;display:none;font-size:17px;left:0;padding:7px 0;position:absolute;text-align:center;top:0;width:100%;z-index:2147483647} body.ytp-contextmenu-hidden .ytp-contextmenu{visibility:hidden!important} .ytp-pause-overlay-hidden .ytp-pause-overlay{display:none!important}";
d.head.appendChild(f);k=d.createElement("div");k.id="efyt-player-info";c.appendChild(k);c.addEventListener("onStateChange",function(b){1!==b||!a.pausevideos||a.ignorepopupplayer||d.hidden||y||(y=!0,d.dispatchEvent(new Event("efyt-pause-videos")),setTimeout(function(){y=!1},1E3));1!==b&&3!==b||!a.selectquality||u||q();1===b?h.classList.add("ytp-pause-overlay-hidden"):2===b?setTimeout(function(){c.classList.remove("ytp-expand-pause-overlay");h.classList.remove("ytp-pause-overlay-hidden")},1E3):0===
b&&(u=!1)});h.classList.add("ytp-pause-overlay-hidden");h.addEventListener("wheel",function(b){if(!c.classList.contains("ytp-settings-shown")&&!c.classList.contains("ytp-menu-shown"))if(b.ctrlKey&&a.controlspeed&&(a.controlspeedmousebutton&&r||!a.controlspeedmousebutton)){b.preventDefault();try{if(a.overridespeeds){var e=g.playbackRate;if(!a.reversemousewheeldirection&&0<b.deltaY||a.reversemousewheeldirection&&0>b.deltaY)e=parseFloat((e-a.speedvariation).toFixed(2)),0>=e&&(e=a.speedvariation),g.playbackRate=
e;else if(!a.reversemousewheeldirection&&0>b.deltaY||a.reversemousewheeldirection&&0<b.deltaY)e=parseFloat((e+a.speedvariation).toFixed(2)),g.playbackRate=e}else{var t=c.getAvailablePlaybackRates();e=c.getPlaybackRate();var v=t.indexOf(e);(!a.reversemousewheeldirection&&0<b.deltaY||a.reversemousewheeldirection&&0>b.deltaY)&&0<v?(e=t[v-1],c.setPlaybackRate(e)):(!a.reversemousewheeldirection&&0>b.deltaY||a.reversemousewheeldirection&&0<b.deltaY)&&v<t.length-1&&(e=t[v+1],c.setPlaybackRate(e))}m=!0;k.textContent=
e+"x";x()}catch(E){}}else if(a.controlvolume&&(a.controlvolumemousebutton&&r||!a.controlvolumemousebutton)){b.preventDefault();try{var l=c.getVolume();!a.reversemousewheeldirection&&0<b.deltaY||a.reversemousewheeldirection&&0>b.deltaY?(l-=a.volumevariation,0>l&&(l=0)):(l+=a.volumevariation,100<l&&(l=100),c.isMuted()&&c.unMute());n=!0;c.setVolume(l);k.textContent=l;x()}catch(E){}}});h.addEventListener("mousedown",function(b){2===b.button&&(a.controlvolumemousebutton||a.controlspeedmousebutton)&&(r=
!0,d.body.classList.add("ytp-contextmenu-hidden"))},!0);h.addEventListener("mouseup",function(b){2===b.button&&(a.controlvolumemousebutton||a.controlspeedmousebutton)&&(r=!1,C?n||m?setTimeout(B,500):d.body.classList.remove("ytp-contextmenu-hidden"):(n||m?(w=!0,setTimeout(B,500)):(w=!1,d.body.classList.remove("ytp-contextmenu-hidden")),n=m=!1))},!0);h.addEventListener("mouseleave",function(){r=n=m=!1;d.body.classList.remove("ytp-contextmenu-hidden")});h.addEventListener("contextmenu",function(b){if(C&&
(a.controlvolumemousebutton&&n||a.controlspeedmousebutton&&m))return b.stopPropagation(),b.preventDefault(),n=m=!1;if((a.controlvolumemousebutton||a.controlspeedmousebutton)&&w)return b.preventDefault(),w=!1},!0);g.addEventListener("click",function(b){if(b.ctrlKey){b.preventDefault();try{var e=b.shiftKey?1:a.speed;a.overridespeeds?g.playbackRate=e:c.setPlaybackRate(e);k.textContent=e+"x";x()}catch(t){}}});a.defaultvolume&&c.setVolume(a.volume);a.overridespeeds?(g.playbackRate=a.speed,g.defaultPlaybackRate=
a.speed):c.setPlaybackRate(a.speed)}d.addEventListener("efyt-set-preferences",function(f){a=p.efyt_embed_prefs});d.dispatchEvent(new Event("efyt-get-preferences"));d.addEventListener("efyt-update-preferences",function(f){a=p.efyt_embed_prefs;c&&(a.selectquality&&(u=!1,q()),a.defaultvolume&&c.setVolume(a.volume),a.overridespeeds?(g.playbackRate=a.speed,g.defaultPlaybackRate=a.speed):c.setPlaybackRate(a.speed))});d.addEventListener("efyt-pause-video",function(f){a.ignorepopupplayer||c.pauseVideo()});
var z;"onfullscreenchange"in d?z="fullscreenchange":"onmozfullscreenchange"in d&&(z="mozfullscreenchange");d.addEventListener(z,function(f){setTimeout(function(){c&&d.fullscreenElement&&a.selectquality&&a.selectqualityfullscreenon?q():c&&!d.fullscreenElement&&a.selectquality&&a.selectqualityfullscreenoff&&q()},500)});var a={},C="Win32"===navigator.platform||"Win64"===navigator.platform,r=!1,m=!1,n=!1,u,y,w,A,h,k,c,g;HTMLVideoElement.prototype.play=function(f){return function(){!this.hasAttribute("efyt")&&
this.classList.contains("html5-main-video")&&(this.setAttribute("efyt",""),g=this,c=this.parentNode.parentNode,h=c.parentNode,a.selectquality&&q(),D());return f.apply(this,arguments)}}(HTMLVideoElement.prototype.play);p.MediaSource&&(MediaSource.isTypeSupported=function(f){return function(b){return a.blockhfrformats&&/framerate=([4-6]\d|\d{3,})/.test(b)||a.blockwebmformats&&/video\/webm/.test(b)?!1:f(b)}}(MediaSource.isTypeSupported))}})(window,document);